# Merges the action vocabulary with the plugged modules' manifests and emits the
# assemblies as {path, body} records. Input: the vocabulary. Arguments: $scopes,
# $manifests, $digest, $out. Run by scrumia-assemble; not useful on its own.

def by_module: map(select(.absent != true)) | INDEX(.module);

# A module contributes to an action when its own manifest says so. Nothing infers a
# provider from a module's name, its slot, or where it happens to be installed.
def providers($M; $mods; $a):
  [ $mods[] as $name
    | $M[$name] // empty
    | . as $m
    | (.provides // [])[]
    | select(.action == $a)
    | { module: $m.module,
        grain: ($m.grain // "cross-cutting"),
        read: (.read // []),
        run: .run,
        entry: .entry } ];

# A caller is declared by the caller, with a file inside itself as evidence. That is a
# provenance fix, not a measurement: a file existing refutes nothing about the call.
def callers($M; $mods; $a):
  [ $mods[] as $name
    | $M[$name] // empty
    | . as $m
    | (.calls // [])[]
    | select(.action == $a)
    | { module: $m.module, from: .from } ];

# project-local < app-level < project-wide, then technology < cross-cutting, then name.
def ordered: sort_by([ .scope_rank,
                       (if .grain == "technology" then 0 else 1 end),
                       .module ]);

def row_line:
  .module as $m
| "| " + ((.i + 1) | tostring)
  + " | `" + .module + "`"
  + " | " + (if (.read | length) > 0
                then (.read | map("`" + $m + "/" + . + "`") | join(", ")) else "—" end)
  + " | " + (if .run then "`" + .run + "`" else "—" end)
  + " | " + (if .entry then "`/" + .entry + "`" else "—" end)
  + " |";

def body($a; $kind; $label; $rows):
    "<!-- generated by scrumia-assemble; do not edit. Rebuild with: scrumia-assemble build -->\n"
  + "# " + $a + " — " + $kind + ", " + $label + "\n\n"
  + "Open the entry fragment of each contributor below. Inside a module, that module's\n"
  + "own routing table and dependency graph order what to open next: this file orders\n"
  + "contributors, never a module's own files.\n\n"
  + "The order is computed, not authored — app-level before project-wide, technology\n"
  + "grain before cross-cutting within a tier, then alphabetical.\n\n"
  + "| # | Module | Open | Run | A person reaches it by |\n|---|---|---|---|---|\n"
  + ([ $rows | to_entries[] | (.value + {i: .key}) | row_line ] | join("\n"))
  + "\n\nEach path above is a module's name followed by a path inside that module. This\n"
  + "file is committed and shared, so it names nothing only one machine can open: run\n"
  + "`scrumia-assemble load " + $a + "` to have the roots resolved, or a module's own\n"
  + "`<module>-manifest` for one of them.\n";

. as $vocab
| ($manifests | by_module) as $M
| (($scopes.project + ["scrumia-core"]) | unique) as $proj
| ( [ { name: "project", label: "project-wide", own: $proj } ]
  + [ $scopes.apps[] | select((.extends | length) > 0)
      | { name: .name, label: ("app `" + .name + "`"), own: .extends } ] ) as $all_scopes

| [ $all_scopes[] as $scope
    | $vocab.actions[] as $act
    | (providers($M; $scope.own; $act.name)
       | map(. + { scope_rank: (if $scope.name == "project" then 2 else 1 end) })) as $own
    | select(($own | length) > 0)
    | ( $own
        + (if $scope.name == "project" then []
           else providers($M; $proj; $act.name) | map(. + {scope_rank: 2}) end)
      ) as $rows
    | { path: (if $scope.name == "project"
               then $out + "/" + $act.name + ".md"
               else $out + "/apps/" + $scope.name + "/" + $act.name + ".md" end),
        body: body($act.name; $act.kind; $scope.label; ($rows | ordered)) } ] as $files

| ( [ $proj, [$scopes.apps[]?.extends] ] | flatten | unique ) as $consulted

| [ $vocab.actions[]
    | select(.set == "run")
    | . as $act
    | ($act.name) as $a
    | (providers($M; $consulted; $a)) as $p
    | { name: $a, kind: $act.kind, step: ($act.step // "—"),
        providers: ($p | map(.module) | unique),
        callers: (callers($M; $consulted; $a) | length),
        entry: ($p | map(.entry) | map(select(. != null)) | first),
        override: ($scopes.overrides[$a] // null) } ] as $run

| ( "<!-- generated by scrumia-assemble; do not edit. Rebuild with: scrumia-assemble build -->\n"
  + "# Composed assemblies\n\n"
  + "Inputs digest: `" + $digest + "`\n\n"
  + "`scrumia-assemble load` refuses when that digest no longer matches and says to\n"
  + "rebuild; it never recomputes an answer on the spot. A plugin version bump does not\n"
  + "invalidate it — these files hold routing, not prose, so a rewritten guide leaves them\n"
  + "correct. A module that changed shape is caught by `scrumia-assemble check` and by the\n"
  + "missing fragment itself.\n\n"
  + "## Modules consulted\n\n| Module | Describes itself through | Actions provided |\n|---|---|---|\n"
  + ([ $consulted[] as $m
       | "| `" + $m + "` | "
       + (if $M[$m] then "`" + $m + "-manifest`" else "**nothing — ships no `composition.json`**" end)
       + " | " + (($M[$m].provides // []) | length | tostring) + " |" ] | join("\n"))
  + "\n\n## Run coverage\n\n"
  + "Coverage counts **module callers**. A person being able to invoke an action does not\n"
  + "remove it from the hole count — it changes the remedy the row offers.\n\n"
  + "| Action | Kind | Step | Provided by | State |\n|---|---|---|---|---|\n"
  + ([ $run[]
       | "| `" + .name + "` | " + .kind + " | " + .step + " | "
       + (if (.providers | length) > 0 then (.providers | map("`" + . + "`") | join(", ")) else "—" end)
       + " | "
       + (if .override == "not-applicable" then "not applicable here — out of the denominator"
          elif .override == "human" then "a person covers it, no tool"
          elif (.providers | length) == 0 then "no provider"
          elif .callers > 0 then "covered — " + (.callers | tostring) + " module caller(s)"
          elif .entry then "hole — no module calls it; a person reaches it by `/" + .entry + "`"
          else "hole — no module calls it, and no entry point" end)
       + " |" ] | join("\n"))
  + "\n" ) as $index

| ($files + [ { path: ($out + "/index.md"), body: $index } ])
| .[]
# NUL-delimited: a body carries newlines, and nothing else survives the round trip.
| .path + "\u0000" + .body + "\u0000"
