#!/usr/bin/env python3
"""Generate features/index.md — the global feature index (ADR-0016).

A leaf feature is a directory under features/ (excluding features/ itself)
that carries an index.md. For each one this reads: the stratum from its path,
the Status line, and the first sentence of "## In brief" as its brief.

Run from anywhere: python3 tools/build_features_index.py
Idempotent; stdlib only, no third-party deps.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FEATURES_ROOT = ROOT / "features"

STATUS_RE = re.compile(r"^\*\*Status\*\*:\s*(.+)$", re.MULTILINE)
IN_BRIEF_RE = re.compile(r"^## In brief\s*\n(.*?)(?=\n## |\Z)", re.MULTILINE | re.DOTALL)


def find_leaf_features(root: Path) -> list[Path]:
    """Every directory under features/ that carries an index.md, features/ itself excluded."""
    features_root = root / "features"
    leaves = [p.parent for p in features_root.rglob("index.md") if p.parent != features_root]
    return sorted(leaves, key=lambda d: d.relative_to(features_root).as_posix())


def stratum_for(feature_dir: Path, features_root: Path) -> str:
    """features/business/<f> -> business; features/app/<app>/<f> -> app/<app>."""
    parts = feature_dir.relative_to(features_root).parts
    if parts[0] == "business":
        return "business"
    if parts[0] == "app" and len(parts) >= 2:
        return f"app/{parts[1]}"
    return parts[0]


def parse_status(text: str) -> str:
    m = STATUS_RE.search(text)
    return m.group(1).strip() if m else ""


def strip_markdown(text: str) -> str:
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def parse_brief(text: str) -> str:
    """First sentence of '## In brief', markdown stripped, cut at the first period or 140 chars."""
    m = IN_BRIEF_RE.search(text)
    if not m:
        return ""
    section = strip_markdown(m.group(1))
    period = section.find(".")
    if period != -1 and period < 140:
        return section[: period + 1]
    # No early sentence boundary: cut at the last word that fits, never mid-word.
    cut = section[:140]
    if " " in cut:
        cut = cut.rsplit(" ", 1)[0]
    return cut.rstrip(" ,;:") + "…"


def generate_index(root: Path) -> str:
    features_root = root / "features"
    lines = [
        "# Features",
        "",
        "<!-- generated by tools/build_features_index.py — do not edit -->",
        "",
        "| Feature | Stratum | Status | In brief |",
        "|---|---|---|---|",
    ]
    for feature_dir in find_leaf_features(root):
        rel = feature_dir.relative_to(features_root)
        text = (feature_dir / "index.md").read_text(encoding="utf-8")
        status = parse_status(text)
        brief = parse_brief(text)
        link = f"{rel.as_posix()}/index.md"
        lines.append(f"| [{feature_dir.name}]({link}) | {stratum_for(feature_dir, features_root)} | {status} | {brief} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    output = generate_index(ROOT)
    (FEATURES_ROOT / "index.md").write_text(output, encoding="utf-8")
    print(f"wrote features/index.md ({len(find_leaf_features(ROOT))} features)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
